services:
  # Backend API Service
  - type: web
    name: promptify-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: promptify-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "https://your-frontend-app.vercel.app"

  # Database
  - type: pserv
    name: promptify-db
    databaseName: promptify
    user: promptify 