services:
  - type: web
    name: promptify-backend
    env: python
    region: oregon
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://promptify-frontend.vercel.app,http://localhost:3000
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: promptify-db
          property: connectionString

databases:
  - name: promptify-db
    databaseName: promptify
    user: promptify_user
    region: oregon 