name: Vercel CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Node.js 설정
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: pnpm 설치
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 의존성 설치
        run: |
          cd frontend
          pnpm install

      - name: 타입 체크
        run: |
          cd frontend
          pnpm type-check

      - name: 린트 검사
        run: |
          cd frontend
          pnpm lint

      - name: 테스트 실행
        run: |
          cd frontend
          pnpm test || echo "테스트 스킵"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Vercel CLI 설치
        run: npm install --global vercel@latest

      - name: Vercel 환경 정보 가져오기
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Vercel 빌드
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Vercel 배포
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} 